spring:
  profiles: 
    active: 
    - dev

spring:
  profiles: dev #开发环境
  application: 
    name: microservice-config-hong-dev 

spring:
  profiles: test #测试环境
  application: 
    name: microservice-config-hong-test

#注意，一定要保存为UTF-8格式    
    